// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/xhdd123321/whicinth-steganography-bd/biz/pkg/redis"
)

func main() {
	h := server.Default()

	redis.InitRedis()

	register(h)
	h.Spin()
}
